
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, July 24, 2006
	Important: Do not modify this file. Edit the file Orders.cs instead.
*/

#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Security.Permissions;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Security;
using System.Data;

using netTiers.Petshop.Entities;
using netTiers.Petshop.Entities.Validation;
using Entities = netTiers.Petshop.Entities;
using netTiers.Petshop.Data;
using netTiers.Petshop.Data.Bases;


using Microsoft.Practices.EnterpriseLibrary.Logging;

#endregion 

namespace netTiers.Petshop.Services
{		
	
	///<summary>
	/// An object representation of the 'Orders' table.
	///</summary>
	/// <remarks>
	/// IMPORTANT!!! You should not modify this partial  class, modify the Orders.cs file instead.
	/// All custom implementations should be done in the <see cref="Orders"/> class.
	/// </remarks>
	[DataObject]
	public partial class OrdersServiceBase : ServiceBase<Orders, OrdersKey>
	{

		#region Constructors
		///<summary>
		/// Creates a new <see cref="Orders"/> instance .
		///</summary>
		public OrdersServiceBase() : base()
		{
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Orders"/> instance.
		///</summary>
		///<param name="accountId"></param>
		///<param name="orderDate"></param>
		///<param name="shipAddr1"></param>
		///<param name="shipAddr2"></param>
		///<param name="shipCity"></param>
		///<param name="shipState"></param>
		///<param name="shipZip"></param>
		///<param name="shipCountry"></param>
		///<param name="billAddr1"></param>
		///<param name="billAddr2"></param>
		///<param name="billCity"></param>
		///<param name="billState"></param>
		///<param name="billZip"></param>
		///<param name="billCountry"></param>
		///<param name="courierId"></param>
		///<param name="totalPrice"></param>
		///<param name="billToFirstName"></param>
		///<param name="billToLastName"></param>
		///<param name="shipToFirstName"></param>
		///<param name="shipToLastName"></param>
		///<param name="creditCardId"></param>
		///<param name="locale"></param>
		public static Orders CreateOrders(System.Guid accountId, System.DateTime orderDate, System.String shipAddr1, System.String shipAddr2, System.String shipCity, System.String shipState, System.String shipZip, System.String shipCountry, System.String billAddr1, System.String billAddr2, System.String billCity, System.String billState, System.String billZip, System.String billCountry, System.Guid courierId, System.Decimal? totalPrice, System.String billToFirstName, System.String billToLastName, System.String shipToFirstName, System.String shipToLastName, System.Guid creditCardId, System.String locale)
		{
			Orders newEntityOrders = new Orders();
			newEntityOrders.AccountId  = accountId;
			newEntityOrders.OrderDate  = orderDate;
			newEntityOrders.ShipAddr1  = shipAddr1;
			newEntityOrders.ShipAddr2  = shipAddr2;
			newEntityOrders.ShipCity  = shipCity;
			newEntityOrders.ShipState  = shipState;
			newEntityOrders.ShipZip  = shipZip;
			newEntityOrders.ShipCountry  = shipCountry;
			newEntityOrders.BillAddr1  = billAddr1;
			newEntityOrders.BillAddr2  = billAddr2;
			newEntityOrders.BillCity  = billCity;
			newEntityOrders.BillState  = billState;
			newEntityOrders.BillZip  = billZip;
			newEntityOrders.BillCountry  = billCountry;
			newEntityOrders.CourierId  = courierId;
			newEntityOrders.TotalPrice  = totalPrice;
			newEntityOrders.BillToFirstName  = billToFirstName;
			newEntityOrders.BillToLastName  = billToLastName;
			newEntityOrders.ShipToFirstName  = shipToFirstName;
			newEntityOrders.ShipToLastName  = shipToLastName;
			newEntityOrders.CreditCardId  = creditCardId;
			newEntityOrders.Locale  = locale;
			return newEntityOrders;
		}
		#endregion Constructors

		#region Fields
		private static SecurityContext<Orders> securityContext = new SecurityContext<Orders>();
		private static readonly string layerExceptionPolicy = "NoneExceptionPolicy";
		private static readonly bool noTranByDefault = false;
		private static readonly int defaultMaxRecords = 10000;
		#endregion 
		
		#region SecurityContext
		///<summary>
		/// Contains all necessary information to validate and authorize the 
		/// call of the method with the Principal and Roles of the current user.
		///</summary>
		public static SecurityContext<Orders> SecurityContext
		{
			get
			{
				return securityContext;	
			}	
		}
		#endregion 
		
		#region Data Access Methods
		
		#region GetByForeignKey Methods
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_Account key.
		///		FK_Orders_Account Description: 
		/// </summary>
		/// <param name="accountId"></param>
		/// <returns>Returns a generic collection of Orders objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByAccountId(System.Guid accountId)
		{
			int totalCount = -1;
			return GetByAccountId(accountId, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_Account key.
		///		FK_Orders_Account Description: 
		/// </summary>
		/// <param name="accountId"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Page length of records you would like to retrieve</param>
		/// <param name="totalCount">Out parameter, number of total rows in given query.</param>
		/// <returns>Returns a collection <see cref="TList{Orders}" /> of <c>Orders</c> objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByAccountId(System.Guid accountId, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetByAccountId");
			
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {					
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Access repository
				list = new TList<Orders>(dataProvider.OrdersProvider.GetByAccountId(transactionManager, accountId, start, pageLength, out totalCount));
				
				//intentionally leave transaction open on a read operation.
				
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_Courier key.
		///		FK_Orders_Courier Description: 
		/// </summary>
		/// <param name="courierId"></param>
		/// <returns>Returns a generic collection of Orders objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByCourierId(System.Guid courierId)
		{
			int totalCount = -1;
			return GetByCourierId(courierId, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_Courier key.
		///		FK_Orders_Courier Description: 
		/// </summary>
		/// <param name="courierId"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Page length of records you would like to retrieve</param>
		/// <param name="totalCount">Out parameter, number of total rows in given query.</param>
		/// <returns>Returns a collection <see cref="TList{Orders}" /> of <c>Orders</c> objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByCourierId(System.Guid courierId, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetByCourierId");
			
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {					
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Access repository
				list = new TList<Orders>(dataProvider.OrdersProvider.GetByCourierId(transactionManager, courierId, start, pageLength, out totalCount));
				
				//intentionally leave transaction open on a read operation.
				
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_CreditCard key.
		///		FK_Orders_CreditCard Description: 
		/// </summary>
		/// <param name="creditCardId"></param>
		/// <returns>Returns a generic collection of Orders objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByCreditCardId(System.Guid creditCardId)
		{
			int totalCount = -1;
			return GetByCreditCardId(creditCardId, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// 	public virtual method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the FK_Orders_CreditCard key.
		///		FK_Orders_CreditCard Description: 
		/// </summary>
		/// <param name="creditCardId"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Page length of records you would like to retrieve</param>
		/// <param name="totalCount">Out parameter, number of total rows in given query.</param>
		/// <returns>Returns a collection <see cref="TList{Orders}" /> of <c>Orders</c> objects.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual TList<Orders> GetByCreditCardId(System.Guid creditCardId, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetByCreditCardId");
			
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {					
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Access repository
				list = new TList<Orders>(dataProvider.OrdersProvider.GetByCreditCardId(transactionManager, creditCardId, start, pageLength, out totalCount));
				
				//intentionally leave transaction open on a read operation.
				
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		#endregion GetByForeignKey Methods
		
		#region GetByIndexes
		/// <summary>
		/// 	Gets a row from the DataSource based on its primary key.
		/// </summary>
		/// <param name="key">The unique identifier of the row to retrieve.</param>
		/// <returns>Returns an instance of the Entity class.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public override Orders  Get(OrdersKey key)
		{
			return GetByOrderId(key.OrderId);
		}
		

		/// <summary>
		///  method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the primary key PK__Orders__0CBAE877 index.
		/// </summary>
		/// <param name="orderId"></param>
		/// <returns>Returns an instance of the <see cref="Orders"/> class.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual Orders GetByOrderId(System.Int32 orderId)
		{
			int totalCount = -1;
			return GetByOrderId(orderId, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		///  Method that Gets rows in a <see cref="TList{Orders}" /> from the datasource based on the primary key PK__Orders__0CBAE877 index.
		/// </summary>
		/// <param name="orderId"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Page length of records you would like to retrieve</param>
		/// <param name="totalCount">out parameter, number of total rows in given query.</param>
		/// <returns>Returns an instance of the <see cref="Orders"/> class.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual Orders GetByOrderId(System.Int32 orderId, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetByOrderId");
			totalCount = -1;
			
			Orders entity = null;
			TransactionManager transactionManager = null; 
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				 transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;					
				
				//Access Repository
				entity = dataProvider.OrdersProvider.GetByOrderId(transactionManager, orderId, start, pageLength)   as Orders;
			
				//if borrowed tran, leave open for next call
				
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return entity;
		}
	
		#endregion GetByIndexes
	
		#region GetList
		/// <summary>
		/// Get a complete collection of <see cref="Orders" /> entities.
		/// </summary>
		/// <returns></returns>
		public override TList<Orders> GetAll() 
		{
			int totalCount = -1;
			return GetAll(0, defaultMaxRecords, out totalCount);
		}

		/// <summary>
		/// Get a set portion of a complete list of <see cref="Orders" /> entities
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter, number of total rows in given query.</param>
		/// <returns>a <see cref="TList{Orders}"/> </returns>
		public virtual TList<Orders> GetAll(int start, int pageLength, out int totalCount) 
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetAll");
			
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;					

				//Access repository
				list = dataProvider.OrdersProvider.GetAll(transactionManager, start, pageLength, out totalCount);	
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a  larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		#endregion GetAll

		#region GetPaged
		/// <summary>
		/// Gets a page of <see cref="TList{Orders}" /> rows from the DataSource.
		/// </summary>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Orders</c> objects.</returns>
		public virtual TList<Orders> GetPaged(out int totalCount)
		{
			return GetPaged(null, null, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// Gets a page of <see cref="TList{Orders}" /> rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Orders</c> objects.</returns>
		public virtual TList<Orders> GetPaged(int start, int pageLength, out int totalCount)
		{
			return GetPaged(null, null, start, pageLength, out totalCount);
		}

		/// <summary>
		/// Gets a page of entity rows with a <see cref="TList{Orders}" /> from the DataSource with a where clause and order by clause.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC).</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Orders</c> objects.</returns>
		public override TList<Orders> GetPaged(string whereClause,string orderBy, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("GetPaged");
			
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.OrdersProvider.GetPaged(transactionManager, whereClause, orderBy, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;			
		}
		
		/// <summary>
		/// Gets the number of rows in the DataSource that match the specified whereClause.
		/// This method is only provided as a workaround for the ObjectDataSource's need to 
		/// execute another method to discover the total count instead of using another param, like our out param.  
		/// This method should be avoided if using the ObjectDataSource or another method.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <returns>Returns the number of rows.</returns>
		public int GetTotalItems(string whereClause, out int totalCount)
		{
			GetPaged(whereClause, null, 0, defaultMaxRecords, out totalCount);
			return totalCount;
		}
		#endregion GetPaged	
				
		#region Find 
		/// <summary>
		/// Attempts to do a parameterized version of a simple whereclause. 
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection of Entity objects.</returns>
		public virtual TList<Orders> Find(string whereClause)
		{
			int totalCount = -1;
			return Find(whereClause, 0, defaultMaxRecords, out totalCount);
		}	
		
		/// <summary>
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter to get total records for query</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection TList{Orders} of <c>Orders</c> objects.</returns>
		public override TList<Orders> Find(string whereClause, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Find");
								
			// get this data
			TList<Orders> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.OrdersProvider.Find(transactionManager, whereClause, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		#endregion
		
		#region Insert

		#region Insert Entity
		/// <summary>
		/// 	public virtualmethod that Inserts a Orders object into the datasource using a transaction.
		/// </summary>
		/// <param name="entity">Orders object to Insert.</param>
		/// <remarks>After Inserting into the datasource, the Orders object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns bool that the operation is successful.</returns>
		/// <example>
        /// The following code shows the usage of the Insert Method with an already open transaction.
        /// <code>
		/// Orders entity = new Orders();
		/// entity.StringProperty = "foo";
		/// entity.IntProperty = 12;
		/// entity.ChildObjectSource.StringProperty = "bar";
		/// TransactionManager tm = null;
		/// try
        ///	{
		/// 	tm = ConnectionContext.CreateTransaction();
		///		//Insert Child entity, Then Parent Entity
		/// 	ChildObjectTypeService.Insert(entity.ChildObjectSource);
		///		OrdersService.Insert(entity);
		///	}
        ///	catch (Exception e)
        ///	{
		///		if (tm != null &amp;&amp; tm.IsOpen) tm.Rollback();
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// </code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Insert)]
		public override bool Insert(Orders entity)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Insert");
			
			if (!entity.IsValid)
				throw new Entities.EntityNotValidException(entity, "Insert");
			
			TransactionManager transactionManager = null; 
			bool result = false;
			
			try
            {	
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Persist Entity
				result = dataProvider.OrdersProvider.Insert(transactionManager, entity); 
				
				//if persisted and tran not borrowed, commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return result;
		}
		#endregion Insert Entity
		
		#region Insert Collection
		/// <summary>
		/// 	public virtual method that Inserts rows in <see cref="TList{Orders}" /> to the datasource.
		/// </summary>
		/// <param name="entityCollection"><c>Orders</c> objects in a <see cref="TList{Orders}" /> object to Insert.</param>
		/// <remarks>
		///		This function will only Insert entity objects marked as dirty
		///		and have an identity field equal to zero.
		///		Upon Inserting the objects, each dirty object will have the public
		///		method <c>Object.AcceptChanges()</c> called to make it clean.
		/// 	After Inserting into the datasource, the <c>Orders</c> objects will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		///</remarks>
		/// <returns>Returns the number of successful Insert.</returns>
		/// <example>
        /// The following code shows the usage of the Insert Method with a collection of Orders.
        /// <code><![CDATA[
		/// TList<Orders> list = new TList<Orders>();
		/// Orders entity = new Orders();
		/// entity.StringProperty = "foo";
		/// Orders entity2 = new Orders();
		/// entity.StringProperty = "bar";
		/// list.Add(entity);
		/// list.Add(entity2);
		///	OrdersService.Insert(list);
		///	}
        ///	catch (Exception e)
        ///	{
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// ]]></code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Insert)]
		public virtual TList<Orders> Insert(TList<Orders> entityCollection)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Insert");
		
			if (!entityCollection.IsValid)
			{
				throw new Entities.EntityNotValidException(entityCollection, "Insert");
			}
			
			TransactionManager transactionManager = null; 
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
                
				//Persist Insert
				dataProvider.OrdersProvider.Insert(transactionManager, entityCollection); 
                
				//If success, Commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			
			return entityCollection;		
		}
		#endregion Insert Collection

		#endregion Insert 
		
		#region Update

		#region Update Entity
		/// <summary>
		/// 	public virtualmethod that Updates a Orders object into the datasource using a transaction.
		/// </summary>
		/// <param name="entity">Orders object to Update.</param>
		/// <remarks>After Updateing into the datasource, the Orders object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns bool that the operation is successful.</returns>
		/// <example>
        /// The following code shows the usage of the Update Method with an already open transaction.
        /// <code>
		///	Orders entity = OrdersService.GetByPrimaryKeyColumn(1234);
		/// entity.StringProperty = "foo";
		/// entity.IntProperty = 12;
		/// entity.ChildObjectSource.StringProperty = "bar";
		/// TransactionManager tm = null;
		/// try
        ///	{
		/// 	tm = ConnectionContext.CreateTransaction();
		///		//Update Child entity, Then Parent Entity
		/// 	ChildObjectTypeService.Update(entity.ChildObjectSource);
		///		OrdersService.Update(entity);
		///	}
        ///	catch (Exception e)
        ///	{
		///		if (tm != null &amp;&amp; tm.IsOpen) tm.Rollback();
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// </code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public override bool Update(Orders entity)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Update");
			
			if (!entity.IsValid)
				throw new Entities.EntityNotValidException(entity, "Update");
			
			TransactionManager transactionManager = null; 
			bool result = false;
			
			try
            {	
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Persist Entity
				result = dataProvider.OrdersProvider.Update(transactionManager, entity); 
				
				//if persisted and tran not borrowed, commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return result;
		}
		#endregion Update Entity
		
		#region Update Collection
		/// <summary>
		/// 	public virtual method that Updates rows in <see cref="TList{Orders}" /> to the datasource.
		/// </summary>
		/// <param name="entityCollection"><c>Orders</c> objects in a <see cref="TList{Orders}" /> object to Update.</param>
		/// <remarks>
		///		This function will only Update entity objects marked as dirty
		///		and have an identity field equal to zero.
		///		Upon Updateing the objects, each dirty object will have the public
		///		method <c>Object.AcceptChanges()</c> called to make it clean.
		/// 	After Updateing into the datasource, the <c>Orders</c> objects will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		///</remarks>
		/// <returns>Returns the number of successful Update.</returns>
		/// <example>
        /// The following code shows the usage of the Update Method with a collection of Orders.
        /// <code><![CDATA[
		/// TList<Orders> list = new TList<Orders>();
		/// Orders entity = new Orders();
		/// entity.StringProperty = "foo";
		/// Orders entity2 = new Orders();
		/// entity.StringProperty = "bar";
		/// list.Add(entity);
		/// list.Add(entity2);
		///	OrdersService.Update(list);
		///	}
        ///	catch (Exception e)
        ///	{
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// ]]></code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public virtual TList<Orders> Update(TList<Orders> entityCollection)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Update");
		
			if (!entityCollection.IsValid)
			{
				throw new Entities.EntityNotValidException(entityCollection, "Update");
			}
			
			TransactionManager transactionManager = null; 
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
                
				//Persist Update
				dataProvider.OrdersProvider.Update(transactionManager, entityCollection); 
                
				//If success, Commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			
			return entityCollection;		
		}
		#endregion Update Collection

		#endregion Update 
		
		#region Save

		#region Save Entity
		/// <summary>
		/// 	public virtualmethod that Saves a Orders object into the datasource using a transaction.
		/// </summary>
		/// <param name="entity">Orders object to Save.</param>
		/// <remarks>After Saveing into the datasource, the Orders object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns bool that the operation is successful.</returns>
		/// <example>
        /// The following code shows the usage of the Save Method with an already open transaction.
        /// <code>
		///	Orders entity = OrdersService.GetByPrimaryKeyColumn(1234);
		/// entity.StringProperty = "foo";
		/// entity.IntProperty = 12;
		/// entity.ChildObjectSource.StringProperty = "bar";
		/// TransactionManager tm = null;
		/// try
        ///	{
		/// 	tm = ConnectionContext.CreateTransaction();
		///		//Save Child entity, Then Parent Entity
		/// 	ChildObjectTypeService.Save(entity.ChildObjectSource);
		///		OrdersService.Save(entity);
		///	}
        ///	catch (Exception e)
        ///	{
		///		if (tm != null &amp;&amp; tm.IsOpen) tm.Rollback();
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// </code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public virtual Orders Save(Orders entity)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Save");
			
			if (!entity.IsValid)
				throw new Entities.EntityNotValidException(entity, "Save");
			
			TransactionManager transactionManager = null; 
			
			try
            {	
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Persist Entity
				dataProvider.OrdersProvider.Save(transactionManager, entity); 
				
				//if persisted and tran not borrowed, commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return entity;
		}
		#endregion Save Entity
		
		#region Save Collection
		/// <summary>
		/// 	public virtual method that Saves rows in <see cref="TList{Orders}" /> to the datasource.
		/// </summary>
		/// <param name="entityCollection"><c>Orders</c> objects in a <see cref="TList{Orders}" /> object to Save.</param>
		/// <remarks>
		///		This function will only Save entity objects marked as dirty
		///		and have an identity field equal to zero.
		///		Upon Saveing the objects, each dirty object will have the public
		///		method <c>Object.AcceptChanges()</c> called to make it clean.
		/// 	After Saveing into the datasource, the <c>Orders</c> objects will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		///</remarks>
		/// <returns>Returns the number of successful Save.</returns>
		/// <example>
        /// The following code shows the usage of the Save Method with a collection of Orders.
        /// <code><![CDATA[
		/// TList<Orders> list = new TList<Orders>();
		/// Orders entity = new Orders();
		/// entity.StringProperty = "foo";
		/// Orders entity2 = new Orders();
		/// entity.StringProperty = "bar";
		/// list.Add(entity);
		/// list.Add(entity2);
		///	OrdersService.Save(list);
		///	}
        ///	catch (Exception e)
        ///	{
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// ]]></code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public virtual TList<Orders> Save(TList<Orders> entityCollection)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Save");
		
			if (!entityCollection.IsValid)
			{
				throw new Entities.EntityNotValidException(entityCollection, "Save");
			}
			
			TransactionManager transactionManager = null; 
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
                
				//Persist Save
				dataProvider.OrdersProvider.Save(transactionManager, entityCollection); 
                
				//If success, Commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			
			return entityCollection;		
		}
		#endregion Save Collection

		#endregion Save 
		
		#region Delete

		#region Delete Entity
		/// <summary>
		/// 	public virtualmethod that Deletes a Orders object into the datasource using a transaction.
		/// </summary>
		/// <param name="entity">Orders object to Delete.</param>
		/// <remarks>After Deleteing into the datasource, the Orders object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns bool that the operation is successful.</returns>
		/// <example>
        /// The following code shows the usage of the Delete Method with an already open transaction.
        /// <code>
		///	Orders entity = OrdersService.GetByPrimaryKeyColumn(1234);
		/// entity.StringProperty = "foo";
		/// entity.IntProperty = 12;
		/// entity.ChildObjectSource.StringProperty = "bar";
		/// TransactionManager tm = null;
		/// try
        ///	{
		/// 	tm = ConnectionContext.CreateTransaction();
		///		//Delete Child entity, Then Parent Entity
		/// 	ChildObjectTypeService.Delete(entity.ChildObjectSource);
		///		OrdersService.Delete(entity);
		///	}
        ///	catch (Exception e)
        ///	{
		///		if (tm != null &amp;&amp; tm.IsOpen) tm.Rollback();
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// </code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Delete)]
		public override bool Delete(Orders entity)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Delete");
			
			if (!entity.IsValid)
				throw new Entities.EntityNotValidException(entity, "Delete");
			
			TransactionManager transactionManager = null; 
			bool result = false;
			
			try
            {	
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Persist Entity
				result = dataProvider.OrdersProvider.Delete(transactionManager, entity); 
				
				//if persisted and tran not borrowed, commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return result;
		}
		#endregion Delete Entity
		
		#region Delete Collection
		/// <summary>
		/// 	public virtual method that Deletes rows in <see cref="TList{Orders}" /> to the datasource.
		/// </summary>
		/// <param name="entityCollection"><c>Orders</c> objects in a <see cref="TList{Orders}" /> object to Delete.</param>
		/// <remarks>
		///		This function will only Delete entity objects marked as dirty
		///		and have an identity field equal to zero.
		///		Upon Deleteing the objects, each dirty object will have the public
		///		method <c>Object.AcceptChanges()</c> called to make it clean.
		/// 	After Deleteing into the datasource, the <c>Orders</c> objects will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		///</remarks>
		/// <returns>Returns the number of successful Delete.</returns>
		/// <example>
        /// The following code shows the usage of the Delete Method with a collection of Orders.
        /// <code><![CDATA[
		/// TList<Orders> list = new TList<Orders>();
		/// Orders entity = new Orders();
		/// entity.StringProperty = "foo";
		/// Orders entity2 = new Orders();
		/// entity.StringProperty = "bar";
		/// list.Add(entity);
		/// list.Add(entity2);
		///	OrdersService.Delete(list);
		///	}
        ///	catch (Exception e)
        ///	{
        ///		if (DomainUtil.HandleException(e, name)) throw;
        ///	}
        /// ]]></code>
        /// </example>
		[DataObjectMethod(DataObjectMethodType.Delete)]
		public virtual TList<Orders> Delete(TList<Orders> entityCollection)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Delete");
		
			if (!entityCollection.IsValid)
			{
				throw new Entities.EntityNotValidException(entityCollection, "Delete");
			}
			
			TransactionManager transactionManager = null; 
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
                
				//Persist Delete
				dataProvider.OrdersProvider.Delete(transactionManager, entityCollection); 
                
				//If success, Commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			
			return entityCollection;		
		}
		#endregion Delete Collection

		#endregion Delete 

		#region   Delete
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="key">The unique identifier of the row to delete.</param>
		/// <returns>Returns true if operation suceeded.</returns>
		public bool Delete(OrdersKey key)
		{
			return Delete(key.OrderId , ((key.Entity != null) ? key.Entity.Timestamp : new byte[0]));
		}
		
		/// <summary>
		/// 	Deletes a row from the DataSource based on the PK'S System.Int32 orderId
		/// </summary>
		/// <param name="orderId">Orders pk id.</param>
		/// <param name="timestamp">The timestamp field used for concurrency check.</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
		[DataObjectMethod(DataObjectMethodType.Delete)]
		public virtual bool Delete(System.Int32 orderId, byte[] timestamp)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("Delete");

			bool result = false;
			TransactionManager transactionManager = null; 
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
                
				//Delete
				result = dataProvider.OrdersProvider.Delete(transactionManager, orderId, timestamp);
	        
				//If success, Commit
				if(!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen)
                        transactionManager.Rollback();
                    
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			
			return result;
			
		}
		#endregion 
		
		#region  GetBy m:m Aggregate Relationships
		#endregion	N2N Relationships

		#region Custom Methods
		#endregion
		
		#region DeepLoad
		#region Deep Load By Entity Keys
		
		/// <summary>
		/// public virtualDeep Loads the requested <see cref="Orders"/> by the entity keys.  The criteria of the child 
		/// property collections only N Levels Deep based on the <see cref="DeepLoadType"/>.
		/// </summary>
		/// <param name="orderId"></param>
		/// <param name="deep">Boolean. A flag that indicates whether to recursively save all Property Collection that are descendants of this instance. If True, saves the complete object graph below this object. If False, saves this object only. </param>
		/// <param name="deepLoadType">DeepLoadType Enumeration to Include/Exclude object property collections from Load.</param>
		/// <param name="childTypes">Orders Property Collection Type Array To Include or Exclude from Load</param>
		/// <returns>Returns an instance of the <see cref="Orders"/> class and DeepLoaded.</returns>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual Orders DeepLoadByOrderId(System.Int32 orderId, bool deep, DeepLoadType deepLoadType, params System.Type[] childTypes)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("DeepLoadByOrderId");		    
			bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;				
	
			Orders entity = GetByOrderId(orderId);
			
			//Check to see if entity is not null, before attempting to Deep Load
			if (entity != null)
				DeepLoad(entity, deep, deepLoadType, childTypes);
			
			return entity;
		}
		
		
		#endregion 

		#region Deep Load By Entity
		/// <summary>
		/// public virtualDeep Load the IEntity object with all of the child 
		/// property collections only 1 Level Deep.
		/// </summary>
		/// <param name="entity">Orders Object</param>
		/// <remarks>
		/// <seealso cref="DeepLoad(Orders)"/> overloaded methods for a recursive N Level deep loading method.
		/// </remarks>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual void DeepLoad(Orders entity)
		{
			DeepLoad(entity, false, DeepLoadType.ExcludeChildren, Type.EmptyTypes);
		}
		
		/// <summary>
		/// public virtualDeep Load the IEntity object with all of the child 
		/// property collections only 1 Level Deep.
		/// </summary>
		/// <remarks>
		/// <seealso cref="DeepLoad(Orders)"/> overloaded methods for a recursive N Level deep loading method.
		/// </remarks>
		/// <param name="entity">Orders Object</param>
		/// <param name="deep">Boolean. A flag that indicates whether to recursively save all Property Collection that are descendants of this instance. If True, saves the complete object graph below this object. If False, saves this object only. </param>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual void DeepLoad(Orders entity, bool deep)
		{
			DeepLoad(entity, deep, DeepLoadType.ExcludeChildren, Type.EmptyTypes);
		}
			
		/// <summary>
		/// public virtualDeep Loads the <see cref="IEntity"/> object with criteria based of the child 
		/// property collections only N Levels Deep based on the <see cref="DeepLoadType"/>.
		/// </summary>
		/// <remarks>
		/// Use this method with caution as it is possible to DeepLoad with Recursion and traverse an entire object graph.
		/// </remarks>
		/// <param name="entity">The <see cref="Orders"/> object to load.</param>
		/// <param name="deep">Boolean. A flag that indicates whether to recursively load all Property Collections that are descendants of this instance. 
		/// If True, saves the complete object graph below this object. If False, saves this object only. </param>
		/// <param name="deepLoadType">DeepLoadType Enumeration to Include/Exclude object property collections from Load.</param>
		/// <param name="childTypes">Orders Property Collection Type Array To Include or Exclude from Load</param>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual void DeepLoad(Orders entity, bool deep, DeepLoadType deepLoadType, params System.Type[] childTypes)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("DeepLoad");
			TransactionManager transactionManager = null; 

			try
            {
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Call Deep Load from the Repository
				dataProvider.OrdersProvider.DeepLoad(transactionManager, entity, deep, deepLoadType, childTypes);
	        
				//leave tran open if used
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen)
                        transactionManager.Rollback();
                    
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			return;
		}
		#endregion
		
		#region Deep Load By Entity Collection
		/// <summary>
		/// Deep Loads the <see cref="TList{Orders}" /> object with all of the child 
		/// property collections only 1 Level Deep.
		/// </summary>
		/// <remarks>
		/// <seealso cref="DeepLoad(Orders)"/> overloaded methods for a recursive N Level deep loading method.
		/// </remarks>
		/// <param name="entityCollection">the <see cref="TList{Orders}" /> Object to deep loads.</param>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual void DeepLoad(TList<Orders> entityCollection)
		{
			DeepLoad(entityCollection, false, DeepLoadType.ExcludeChildren, Type.EmptyTypes);
		}
		
		/// <summary>
		/// Deep Loads the <see cref="TList{Orders}" /> object.
		/// </summary>
		/// <remarks>
		/// <seealso cref="DeepLoad(Orders)"/> overloaded methods for a recursive N Level deep loading method.
		/// </remarks>
		/// <param name="entityCollection">the <see cref="TList{Orders}" /> Object to deep loads.</param>
		/// <param name="deep">Boolean. A flag that indicates whether to recursively save all Property Collection that are descendants of this instance. If True, saves the complete object graph below this object. If False, saves this object only. </param>
		[DataObjectMethod(DataObjectMethodType.Select)]
		public virtual void DeepLoad(TList<Orders> entityCollection, bool deep)
		{
			DeepLoad(entityCollection, deep, DeepLoadType.ExcludeChildren, Type.EmptyTypes);
		}	

		/// <summary>
		/// Deep Loads the entire <see cref="TList{Orders}" /> object with criteria based of the child 
		/// property collections only N Levels Deep based on the DeepLoadType.
		/// </summary>
		/// <remarks>
		/// Use this method with caution as it is possible to DeepLoad with Recursion and traverse an entire collection's object graph.
		/// </remarks>
		/// <param name="entityCollection">The <see cref="TList{Orders}" /> instance to load.</param>
		/// <param name="deep">Boolean. A flag that indicates whether to recursively save all Property Collection that are descendants of this instance. If True, saves the complete object graph below this object. If False, saves this object only. </param>
		/// <param name="deepLoadType"><see cref="DeepLoadType"/> Enumeration to Include/Exclude object property collections from Load.
		///		Use DeepLoadType.IncludeChildren, ExcludeChildren to traverse the entire object graph.
		///	</param>
		/// <param name="childTypes"><see cref="Orders"/> Property Collection Type Array To Include or Exclude from Load</param>
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public override void DeepLoad(TList<Orders> entityCollection, bool deep, DeepLoadType deepLoadType, params System.Type[] childTypes)
		{	
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("DeepLoad");
			TransactionManager transactionManager = null; 

			try
            {
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Call Deep Load from the Repository
				dataProvider.OrdersProvider.DeepLoad(transactionManager, entityCollection, deep, deepLoadType, childTypes);
	        
				//leave transaction open if used, this read is part of a larger transaction
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen)
                        transactionManager.Rollback();
                    
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
            }
			return;		
		}
		#endregion

		#endregion
		
		#region DeepSave
		
		#region Deep Save By Entity
		/// <summary>
		/// public virtualDeep Saves the <see cref="Orders"/> object with all of the child
		/// property collections N Levels Deep.
		/// </summary>
		/// <param name="entity">Orders Object</param>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public virtual bool DeepSave(Orders entity)
		{
			return DeepSave(entity, DeepSaveType.ExcludeChildren, Type.EmptyTypes);
		}
		
		/// <summary>
		/// public virtualDeep Saves the entire object graph of the Orders object with criteria based of the child 
		/// Type property array and DeepSaveType.
		/// </summary>
		/// <param name="entity">Orders Object</param>
		/// <param name="deepSaveType">DeepSaveType Enumeration to Include/Exclude object property collections from Save.</param>
		/// <param name="childTypes"><c>Orders</c> property Type Array To Include or Exclude from Save</param>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public override bool DeepSave(Orders entity, DeepSaveType deepSaveType, params System.Type[] childTypes)
		{
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("DeepSave");
			
			if (!entity.IsValid)
			{
				throw new Entities.EntityNotValidException(entity, "DeepSave");
			}
			
			bool result = false;
			TransactionManager transactionManager = null; 
			
			try
            {	
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				
				//Save
				result = dataProvider.OrdersProvider.DeepSave(transactionManager, entity, deepSaveType, childTypes);
				
				//If success, Commit
				if (!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
            	
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen)
                        transactionManager.Rollback();
                
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;

            }
			return result;		
		}
		#endregion
		
		#region Deep Save By Entity Collection
		/// <summary>
		/// Deep Save the entire <see cref="TList{Orders}" /> object with all of the child 
		/// property collections.
		/// </summary>
		/// <param name="entityCollection">TList{Orders} Object</param>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public virtual bool DeepSave(TList<Orders> entityCollection)
		{
			return DeepSave(entityCollection, DeepSaveType.ExcludeChildren, Type.EmptyTypes);
		}
		
		/// <summary>
		/// Deep Save the entire object graph of the <see cref="TList{Orders}" /> object with criteria based of the child 
		/// property collections.
		/// </summary>
		/// <param name="entityCollection"><see cref="TList{Orders}" /> Object</param>
		/// <param name="deepSaveType">DeepSaveType Enumeration to Include/Exclude object property collections from Save.</param>
		/// <param name="childTypes">Orders Property Collection Type Array To Include or Exclude from Save</param>
		[DataObjectMethod(DataObjectMethodType.Update)]
		public override bool DeepSave(TList<Orders> entityCollection, DeepSaveType deepSaveType, params System.Type[] childTypes)
		{				
			// throws security exception if not authorized
			SecurityContext.IsAuthorized("DeepSave");
			
			if (!entityCollection.IsValid)
			{
				throw new Entities.EntityNotValidException(entityCollection, "DeepSave");
			}
			
			bool result = false;
			TransactionManager transactionManager = null; 
			
			try
            {
				bool isBorrowedTransaction = ConnectionScope.Current.HasTransaction;
				
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction();
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
				result = dataProvider.OrdersProvider.DeepSave(transactionManager, entityCollection,  deepSaveType, childTypes);
				
				//If success and not borrowed, Commit
				if (!isBorrowedTransaction && transactionManager != null && transactionManager.IsOpen)
					transactionManager.Commit();
			}
            catch (Exception exc)
            {
				//if open, rollback
                if (transactionManager != null && transactionManager.IsOpen)
                    transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;

            }
			return result;
		}
		#endregion

		#endregion 

		#endregion Data Access Methods
			
	}//End Class
} // end namespace


