	
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, July 24, 2006
	Important: Do not modify this file. Edit the file LineItem.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace netTiers.Petshop.Entities
{
	#region LineItemEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="LineItem"/> object.
	/// </remarks>
	public class LineItemEventArgs : System.EventArgs
	{
		private LineItemColumn column;
		
		///<summary>
		/// Initalizes a new Instance of the LineItemEventArgs class.
		///</summary>
		public LineItemEventArgs(LineItemColumn column)
		{
			this.column = column;
		}
		
		
		///<summary>
		/// The LineItemColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LineItemColumn" />
		public LineItemColumn Column { get { return this.column; } }
	}
	#endregion
	
	
	///<summary>
	/// Define a delegate for all LineItem related events.
	///</summary>
	public delegate void LineItemEventHandler(object sender, LineItemEventArgs e);
	
	///<summary>
	/// An object representation of the 'LineItem' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	//[ToolboxItem(typeof(LineItem))]
	public abstract partial class LineItemBase : EntityBase, IEntityId<LineItemKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		/// 	Old the inner data of the entity.
		/// </summary>
		private LineItemEntityData entityData;
		
		// <summary>
		// 	Old the original data of the entity.
		// </summary>
		//LineItemEntityData originalData;
		
		/// <summary>
		/// 	Old a backup of the inner data of the entity.
		/// </summary>
		private LineItemEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		[NonSerialized]
		private TList<LineItem> parentCollection;
		private bool inTxn = false;

		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event LineItemEventHandler ColumnChanging;
		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LineItemEventHandler ColumnChanged;		
		#endregion "Variable Declarations"
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LineItemBase"/> instance.
		///</summary>
		public LineItemBase()
		{
			this.entityData = new LineItemEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LineItemBase"/> instance.
		///</summary>
		///<param name="lineItemOrderId"></param>
		///<param name="lineItemLineNum"></param>
		///<param name="lineItemItemId"></param>
		///<param name="lineItemQuantity"></param>
		///<param name="lineItemUnitPrice"></param>
		public LineItemBase(System.Int32 lineItemOrderId, System.Int32 lineItemLineNum, System.Guid lineItemItemId, 
			System.Int32 lineItemQuantity, System.Decimal lineItemUnitPrice)
		{
			this.entityData = new LineItemEntityData();
			this.backupData = null;

			this.OrderId = lineItemOrderId;
			this.LineNum = lineItemLineNum;
			this.ItemId = lineItemItemId;
			this.Quantity = lineItemQuantity;
			this.UnitPrice = lineItemUnitPrice;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="LineItem"/> instance.
		///</summary>
		///<param name="lineItemOrderId"></param>
		///<param name="lineItemLineNum"></param>
		///<param name="lineItemItemId"></param>
		///<param name="lineItemQuantity"></param>
		///<param name="lineItemUnitPrice"></param>
		public static LineItem CreateLineItem(System.Int32 lineItemOrderId, System.Int32 lineItemLineNum, System.Guid lineItemItemId, 
			System.Int32 lineItemQuantity, System.Decimal lineItemUnitPrice)
		{
			LineItem newLineItem = new LineItem();
			newLineItem.OrderId = lineItemOrderId;
			newLineItem.LineNum = lineItemLineNum;
			newLineItem.ItemId = lineItemItemId;
			newLineItem.Quantity = lineItemQuantity;
			newLineItem.UnitPrice = lineItemUnitPrice;
			return newLineItem;
		}
				
		#endregion Constructors
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LineItemColumn"/> which has raised the event.</param>
		public void OnColumnChanging(LineItemColumn column)
		{
			if(IsEntityTracked && EntityState != EntityState.Added)
				EntityManager.StopTracking(EntityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				LineItemEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LineItemEventArgs(column));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LineItemColumn"/> which has raised the event.</param>
		public void OnColumnChanged(LineItemColumn column)
		{
			if (!SuppressEntityEvents)
			{
				LineItemEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LineItemEventArgs(column));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
				
		#region Properties	
				
		/// <summary>
		/// 	Gets or sets the OrderId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(true,false,false)]
		public virtual System.Int32 OrderId
		{
			get
			{
				return this.entityData.OrderId; 
			}
			
			set
			{
				if (this.entityData.OrderId == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.OrderId);
				this.entityData.OrderId = value;
				this.EntityId.OrderId = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.OrderId);
				OnPropertyChanged("OrderId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the OrderId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the OrderId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalOrderId
		{
			get { return this.entityData.OriginalOrderId; }
			set { this.entityData.OriginalOrderId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the LineNum property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(true,false,false)]
		public virtual System.Int32 LineNum
		{
			get
			{
				return this.entityData.LineNum; 
			}
			
			set
			{
				if (this.entityData.LineNum == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.LineNum);
				this.entityData.LineNum = value;
				this.EntityId.LineNum = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.LineNum);
				OnPropertyChanged("LineNum");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the LineNum property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the LineNum property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalLineNum
		{
			get { return this.entityData.OriginalLineNum; }
			set { this.entityData.OriginalLineNum = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the ItemId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false,false,false)]
		public virtual System.Guid ItemId
		{
			get
			{
				return this.entityData.ItemId; 
			}
			
			set
			{
				if (this.entityData.ItemId == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.ItemId);
				this.entityData.ItemId = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.ItemId);
				OnPropertyChanged("ItemId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Quantity property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false,false,false)]
		public virtual System.Int32 Quantity
		{
			get
			{
				return this.entityData.Quantity; 
			}
			
			set
			{
				if (this.entityData.Quantity == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.Quantity);
				this.entityData.Quantity = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.Quantity);
				OnPropertyChanged("Quantity");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UnitPrice property. 
		///		
		/// </summary>
		/// <value>This type is money.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false,false,false)]
		public virtual System.Decimal UnitPrice
		{
			get
			{
				return this.entityData.UnitPrice; 
			}
			
			set
			{
				if (this.entityData.UnitPrice == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.UnitPrice);
				this.entityData.UnitPrice = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.UnitPrice);
				OnPropertyChanged("UnitPrice");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Timestamp property. 
		///		
		/// </summary>
		/// <value>This type is timestamp.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false,false,false)]
		public virtual System.Byte[] Timestamp
		{
			get
			{
				return this.entityData.Timestamp; 
			}
			
			set
			{
				if (this.entityData.Timestamp == value)
					return;
					
					
				OnColumnChanging(LineItemColumn.Timestamp);
				this.entityData.Timestamp = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(LineItemColumn.Timestamp);
				OnPropertyChanged("Timestamp");
			}
		}
		

		#region Source Foreign Key Property
				
		private Orders _orderIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Orders"/>.
		/// </summary>
		/// <value>The source Orders for OrderId.</value>
		[Browsable(false), BindableAttribute()]
		public virtual Orders OrderIdSource
      	{
            get { return this._orderIdSource; }
            set { this._orderIdSource = value; }
      	}
		private Item _itemIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Item"/>.
		/// </summary>
		/// <value>The source Item for ItemId.</value>
		[Browsable(false), BindableAttribute()]
		public virtual Item ItemIdSource
      	{
            get { return this._itemIdSource; }
            set { this._itemIdSource = value; }
      	}
		#endregion
			
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "LineItem"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"OrderId", "LineNum", "ItemId", "Quantity", "UnitPrice", "Timestamp"};
			}
		}
		#endregion 
		
		
		#endregion
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LineItemEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (LineItem) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return (object)this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = (TList<LineItem>)value;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as LineItem);
	        }
	    }


		#endregion
		
		#region Methods	
			
		///<summary>
		///  TODO: Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public override void CancelChanges()
		{
			throw new NotImplementedException("Method currently not Supported.");
		}	
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed LineItem Entity 
		///</summary>
		public virtual LineItem Copy()
		{
			//shallow copy entity
			LineItem copy = new LineItem();
			copy.OrderId = this.OrderId;
			copy.OriginalOrderId = this.OriginalOrderId;
			copy.LineNum = this.LineNum;
			copy.OriginalLineNum = this.OriginalLineNum;
			copy.ItemId = this.ItemId;
			copy.Quantity = this.Quantity;
			copy.UnitPrice = this.UnitPrice;
			copy.Timestamp = this.Timestamp;
					
			copy.AcceptChanges();
			return (LineItem)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed LineItem Entity which is a deep copy of the current entity.
		///</summary>
		public virtual LineItem DeepCopy()
		{
			return EntityHelper.Clone<LineItem>(this as LineItem);	
		}
		#endregion
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LineItemBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LineItemBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="LineItemBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="LineItemBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LineItemBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(LineItemBase Object1, LineItemBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.OrderId != Object2.OrderId)
				equal = false;
			if (Object1.LineNum != Object2.LineNum)
				equal = false;
			if (Object1.ItemId != Object2.ItemId)
				equal = false;
			if (Object1.Quantity != Object2.Quantity)
				equal = false;
			if (Object1.UnitPrice != Object2.UnitPrice)
				equal = false;
			if (Object1.Timestamp != Object2.Timestamp)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			// TODO -> generate a strongly typed IComparer in the concrete class
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name) .CompareTo(((LineItemBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name));
		}
		
		/*
		// static method to get a Comparer object
        public static LineItemComparer GetComparer()
        {
            return new LineItemComparer();
        }
        */

        // Comparer delegates back to LineItem
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(LineItem rhs, LineItemColumn which)
        {
            switch (which)
            {
            	
            	
            	case LineItemColumn.OrderId:
            		return this.OrderId.CompareTo(rhs.OrderId);
            		
            		                 
            	
            	
            	case LineItemColumn.LineNum:
            		return this.LineNum.CompareTo(rhs.LineNum);
            		
            		                 
            	
            	
            	case LineItemColumn.ItemId:
            		return this.ItemId.CompareTo(rhs.ItemId);
            		
            		                 
            	
            	
            	case LineItemColumn.Quantity:
            		return this.Quantity.CompareTo(rhs.Quantity);
            		
            		                 
            	
            	
            	case LineItemColumn.UnitPrice:
            		return this.UnitPrice.CompareTo(rhs.UnitPrice);
            		
            		                 
            	
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public void Dispose()
		{
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LineItemKey> Members
		
		// member variable for the EntityId property
		private LineItemKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public LineItemKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LineItemKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = @"LineItem" 
					+ this.OrderId.ToString()
					+ this.LineNum.ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- OrderId: {0}{6}- LineNum: {1}{6}- ItemId: {2}{6}- Quantity: {3}{6}- UnitPrice: {4}{6}- Timestamp: {5}{6}", 
				this.OrderId,
				this.LineNum,
				this.ItemId,
				this.Quantity,
				this.UnitPrice,
				this.Timestamp,
				Environment.NewLine, 
				this.GetType());
		}
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'LineItem' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal class LineItemEntityData : ICloneable
	{
		#region Variable Declarations
		
		#region Primary key(s)
			/// <summary>			
			/// OrderId : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "LineItem"</remarks>
			public System.Int32 OrderId;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Int32 OriginalOrderId;
			
			/// <summary>			
			/// LineNum : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "LineItem"</remarks>
			public System.Int32 LineNum;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Int32 OriginalLineNum;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ItemId : 
		/// </summary>
		public System.Guid		  ItemId = Guid.Empty;
		
		/// <summary>
		/// Quantity : 
		/// </summary>
		public System.Int32		  Quantity = (int)0;
		
		/// <summary>
		/// UnitPrice : 
		/// </summary>
		public System.Decimal		  UnitPrice = 0;
		
		/// <summary>
		/// Timestamp : 
		/// </summary>
		public System.Byte[]		  Timestamp = new byte[] {};
		#endregion
			
		#endregion "Variable Declarations"
		
		public Object Clone()
		{
			LineItemEntityData _tmp = new LineItemEntityData();
						
			_tmp.OrderId = this.OrderId;
			_tmp.OriginalOrderId = this.OriginalOrderId;
			_tmp.LineNum = this.LineNum;
			_tmp.OriginalLineNum = this.OriginalLineNum;
			
			_tmp.ItemId = this.ItemId;
			_tmp.Quantity = this.Quantity;
			_tmp.UnitPrice = this.UnitPrice;
			_tmp.Timestamp = this.Timestamp;
			
			return _tmp;
		}
		
	}//End struct


		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(Validation.CommonRules.NotNull,"Timestamp");
		}
   		#endregion
	
	} // End Class
	
	#region LineItemComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LineItemComparer : System.Collections.Generic.IComparer<LineItem>
	{
		LineItemColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LineItemComparer"/> class.
        /// </summary>
		public LineItemComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:%=className%>Comparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LineItemComparer(LineItemColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="LineItem"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="LineItem"/> to compare.</param>
        /// <param name="b">The second <c>LineItem</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(LineItem a, LineItem b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(LineItem entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(LineItem a, LineItem b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LineItemColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LineItemKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="LineItem"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LineItemKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LineItemKey class.
		/// </summary>
		public LineItemKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LineItemKey class.
		/// </summary>
		public LineItemKey(LineItemBase entity)
		{
			Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.orderId = entity.OrderId;
				this.lineNum = entity.LineNum;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LineItemKey class.
		/// </summary>
		public LineItemKey(System.Int32 orderId, System.Int32 lineNum)
		{
			#region Init Properties

			this.orderId = orderId;
			this.lineNum = lineNum;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LineItemBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LineItemBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the OrderId property
		private System.Int32 orderId;
		
		/// <summary>
		/// Gets or sets the OrderId property.
		/// </summary>
		public System.Int32 OrderId
		{
			get { return orderId; }
			set
			{
				if ( Entity != null )
				{
					Entity.OrderId = value;
				}
				
				orderId = value;
			}
		}
		
		// member variable for the LineNum property
		private System.Int32 lineNum;
		
		/// <summary>
		/// Gets or sets the LineNum property.
		/// </summary>
		public System.Int32 LineNum
		{
			get { return lineNum; }
			set
			{
				if ( Entity != null )
				{
					Entity.LineNum = value;
				}
				
				lineNum = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				OrderId = ( values["OrderId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["OrderId"], typeof(System.Int32)) : (int)0;
				LineNum = ( values["LineNum"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["LineNum"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("OrderId", OrderId);
			values.Add("LineNum", LineNum);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("OrderId: {0}{2}LineNum: {1}{2}",
								OrderId,
								LineNum,
								Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	
	
	/// <summary>
	/// Enumerate the LineItem columns.
	/// </summary>
	[Serializable]
	public enum LineItemColumn
	{
		/// <summary>
		/// OrderId : 
		/// </summary>
		[EnumTextValue("OrderId")]
		OrderId,
		/// <summary>
		/// LineNum : 
		/// </summary>
		[EnumTextValue("LineNum")]
		LineNum,
		/// <summary>
		/// ItemId : 
		/// </summary>
		[EnumTextValue("ItemId")]
		ItemId,
		/// <summary>
		/// Quantity : 
		/// </summary>
		[EnumTextValue("Quantity")]
		Quantity,
		/// <summary>
		/// UnitPrice : 
		/// </summary>
		[EnumTextValue("UnitPrice")]
		UnitPrice,
		/// <summary>
		/// Timestamp : 
		/// </summary>
		[EnumTextValue("Timestamp")]
		Timestamp
	}//End enum

} // end namespace


