

/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, July 24, 2006
	Important: Do not modify this file. Edit the file OrderStatusTypeTest.cs instead.
*/

#region Using directives

using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using netTiers.Petshop.Entities;
using netTiers.Petshop.Data;

#endregion

namespace netTiers.Petshop.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="OrderStatusType"/> objects (entity, collection and repository).
    /// </summary>
   public partial class OrderStatusTypeTest
    {
    	// the OrderStatusType instance used to test the repository.
		static private OrderStatusType mock;
		
		// the TList<OrderStatusType> instance used to test the repository.
		static TList<OrderStatusType> mockCollection;
		
		static TransactionManager transactionManager = null;
        
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {
			mock = (OrderStatusType)CreateMockInstance();						
			
        	if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction();
			}
			
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the OrderStatusType Entity with the {0} --", netTiers.Petshop.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   
        	if (DataRepository.Provider.IsTransactionSupported && transactionManager!=null && transactionManager.IsOpen)
			{
				transactionManager.Rollback();
			}
			
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock OrderStatusType entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			Assert.IsTrue(DataRepository.OrderStatusTypeProvider.Insert(transactionManager, mock), "Insert failed");
									
			System.Console.WriteLine("DataRepository.OrderStatusTypeProvider.Insert(mock):");			
			System.Console.WriteLine(mock);			
		}
		
		
		/// <summary>
		/// Selects all OrderStatusType objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			mockCollection = DataRepository.OrderStatusTypeProvider.GetAll(transactionManager);
			Assert.IsTrue(mockCollection.Count > 0, "No records returned.");
			System.Console.WriteLine("DataRepository.OrderStatusTypeProvider.GetAll():");			
			System.Console.WriteLine(mockCollection);
					
			
			// get paged
			int count = 0;
			DataRepository.OrderStatusTypeProvider.GetPaged(transactionManager, 0, 10, out count);
			System.Console.WriteLine("#get paged count: " + count.ToString());
		}
		
		
		
		
		/// <summary>
		/// Deep load all OrderStatusType children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			if (mockCollection.Count > 0)
			{
				//mockCollection.Shuffle();			
				DataRepository.OrderStatusTypeProvider.DeepLoad(mockCollection[0]);
				System.Console.WriteLine("OrderStatusType instance correctly deep loaded at 1 level.");
								
				mockCollection.Add(mock);
				DataRepository.OrderStatusTypeProvider.DeepSave(transactionManager, mockCollection);
			}			
		}
		
		/// <summary>
		/// Updates a mock OrderStatusType entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			UpdateMockInstance(mock);
			Assert.IsTrue(DataRepository.OrderStatusTypeProvider.Update(transactionManager, mock), "Update failed.");			
		
			// TODO : select sur l'id
			// TODO : verif si l'object recup? est egal
			
			System.Console.WriteLine("DataRepository.OrderStatusTypeProvider.Update(mock):");			
			System.Console.WriteLine(mock);
		}
		
		
		/// <summary>
		/// Delete the mock OrderStatusType entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			Assert.IsTrue(DataRepository.OrderStatusTypeProvider.Delete(transactionManager, mock), "Delete failed.");
			System.Console.WriteLine("DataRepository.OrderStatusTypeProvider.Delete(mock):");			
			System.Console.WriteLine(mock);
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock OrderStatusType entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{
			string fileName = "temp_OrderStatusType.xml";
		
			//XmlSerializer mySerializer = new XmlSerializer(typeof(OrderStatusType)); 
			//StreamWriter myWriter = new StreamWriter(fileName); 
			//mySerializer.Serialize(myWriter, this.mock); 
			//myWriter.Close();
			EntityHelper.SerializeXml(mock, fileName);
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock OrderStatusType entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = "temp_OrderStatusType.xml";
		
			//XmlSerializer mySerializer = new XmlSerializer(typeof(OrderStatusType)); 
			//FileStream myFileStream = new FileStream(fileName,  FileMode.Open); 
			//this.mock = (OrderStatusType) mySerializer.Deserialize(myFileStream);
			//myFileStream.Close();
			StreamReader sr = File.OpenText(fileName);
			object item = EntityHelper.DeserializeEntityXml<OrderStatusType>(sr.ReadToEnd());
			sr.Close();
			File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a OrderStatusType collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			string fileName = "temp_OrderStatusTypeCollection.xml";
		
			TList<OrderStatusType> mockCollection = new TList<OrderStatusType>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<OrderStatusType>)); 
			StreamWriter myWriter = new StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("TList<OrderStatusType> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a OrderStatusType collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = "temp_OrderStatusTypeCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<OrderStatusType>)); 
			FileStream myFileStream = new FileStream(fileName,  FileMode.Open); 
			TList<OrderStatusType> mockCollection = (TList<OrderStatusType>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			File.Delete(fileName);
			System.Console.WriteLine("TList<OrderStatusType> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			OrderStatusType entity = mockCollection[0].Clone() as OrderStatusType;
			
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			OrderStatusType entity = mockCollection[0].Clone() as OrderStatusType;
			
			OrderStatusType t0 = DataRepository.OrderStatusTypeProvider.GetByOrderStatusId(transactionManager, entity.OrderStatusId);
			OrderStatusType t1 = DataRepository.OrderStatusTypeProvider.GetByOrderStatus(transactionManager, entity.OrderStatus);
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			OrderStatusType entity = mock.Copy() as OrderStatusType;
			//Assert.IsTrue(EntityHelper.AreObjectsEqual(entity, mock), "Copy is working");

			entity = (OrderStatusType)mock.Clone();
			//Assert.IsTrue(EntityHelper.AreObjectsEqual(entity, mock), "Clone is working");
			
			Assert.IsTrue(entity.Equals(mock), "Clone is working");


			//Assert.IsTrue(EntityHelper.AreObjectsEqual(mockCollection[0], mockCollection[0]), "AreObjectEqual");
		}
		
		
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed OrderStatusType Entity with mock values.
		///</summary>
		static public OrderStatusType CreateMockInstance()
		{		
			OrderStatusType mock = new OrderStatusType();
						
			mock.OrderStatus = "MBMYEEWZJJK";
			mock.OrderStatusDescription = "POYJMURFLGCVC[HCNKSAQKFCIJBASCFSGTRGMYWPXDKEMABVSYTXYWBEJWCDTRNJBJPJIBQPNEDNBBQIJGIUJIVKSNWQXTWGQBDDLSMRHEJUTODIGUUNJSZSPFRVFASUIXX[YNWRURNFZBREKOLDZ";
			
		
			// create a temporary collection and add the item to it
			TList<OrderStatusType> tempMockCollection = new TList<OrderStatusType>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (OrderStatusType)mock;
		}
		
		
		///<summary>
		///  Update the Typed OrderStatusType Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance(OrderStatusType mock)
		{
			mock.OrderStatus = "MBMYEEWZJJK2";
			mock.OrderStatusDescription = "POYJMURFLGCVC[HCNKSAQKFCIJBASCFSGTRGMYWPXDKEMABVSYTXYWBEJWCDTRNJBJPJIBQPNEDNBBQIJGIUJIVKSNWQXTWGQBDDLSMRHEJUTODIGUUNJSZSPFRVFASUIXX[YNWRURNFZBREKOLDZ2";
			
		}

		#endregion
    }
}
